### ISSUE TITLE
errors in partial and full pipeline

### ISSUE THREAD

**Issue by danessel** [nPhasePipeline/nPhase#3] opened 2020-09-21 11:54 UTC
Hi, very interesting tool for us. I tried the following but ancountered an error:
nphase partial --sampleName $samplename --reference $reference --output ./ --mappedShortReads $mappedShortReads \
               --longReads $longreads --mappedLongReads $mappedONTread

Traceback (most recent call last):
  File "/media/bulk_01/users/essel002/anaconda3/envs/polyploidPhasing/bin/nphase", line 11, in <module>
    sys.exit(main())
  File "/media/bulk_01/users/essel002/anaconda3/envs/polyploidPhasing/lib/python3.8/site-packages/bin/nPhasePipeline.py", line 513, in main
    partialPipeline(args)
  File "/media/bulk_01/users/essel002/anaconda3/envs/polyploidPhasing/lib/python3.8/site-packages/bin/nPhasePipeline.py", line 333, in partialPipeline
    shortReadBam==args.mappedShortReads
UnboundLocalError: local variable 'shortReadBam' referenced before assignment

Any idea ?

I also ried the whole pipeline but after the markduplicate step the bam file seems to be removed and sorting the bam files gives the error
Here is the error part in the log file:
INFO    2020-09-14 15:25:16     MarkDuplicates  Read   448,000,000 records.  Elapsed time: 08:23:29s.  Time for last 1,000,000: 1,100s.  Last read position: StSOLv1.1ch01:34,366,000
INFO    2020-09-14 15:25:16     MarkDuplicates  Tracking 55877209 as yet unmatched pairs. 55877209 records in RAM.
INFO    2020-09-14 15:47:00     MarkDuplicates  Read   449,000,000 records.  Elapsed time: 08:45:13s.  Time for last 1,000,000: 1,303s.  Last read position: StSOLv1.1ch01:34,414,428
INFO    2020-09-14 15:47:00     MarkDuplicates  Tracking 55885188 as yet unmatched pairs. 55885188 records in RAM.
INFO    2020-09-14 16:18:50     MarkDuplicates  Read   450,000,000 records.  Elapsed time: 09:17:03s.  Time for last 1,000,000: 1,909s.  Last read position: StSOLv1.1ch01:34,477,480
INFO    2020-09-14 16:18:50     MarkDuplicates  Tracking 55925108 as yet unmatched pairs. 55925108 records in RAM.
[Mon Sep 14 16:51:18 CEST 2020] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 589.56 minutes.
Runtime.totalMemory()=29487529984
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.lang.reflect.Array.newArray(Native Method)
        at java.lang.reflect.Array.newInstance(Array.java:75)
        at java.util.Arrays.parallelSort(Arrays.java:1178)
        at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:247)
        at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:182)
        at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:553)
        at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
Using GATK jar /media/bulk_01/users/essel002/anaconda3/envs/polyploidPhasing/share/gatk4-4.1.8.1-0/gatk-package-4.1.8.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /media/bulk_01/users/essel002/anaconda3/envs/polyploidPhasing/share/gatk4-4.1.8.1-0/gatk-package-4.1.8.1-local.jar MarkDuplicates --REMOVE_DUPLICATES true -I ./StSOLv1.1ch01.Colomba/Mapped/shortReads/StSOLv1.1ch01.Colomba.sorted.bam -O ./StSOLv1.1ch01.Colomba/Mapped/shortReads/StSOLv1.1ch01.Colomba.sorted.MD.bam -M /dev/null

STDOUT:

COMMAND: samtools sort ./StSOLv1.1ch01.Colomba/Mapped/shortReads/StSOLv1.1ch01.Colomba.sorted.MD.bam -o ./StSOLv1.1ch01.Colomba/Mapped/shortReads/StSOLv1.1ch01.Colomba.final.bam

STDERR:

[E::hts_open_format] Failed to open file ./StSOLv1.1ch01.Colomba/Mapped/shortReads/StSOLv1.1ch01.Colomba.sorted.MD.bam
samtools sort: can't open "./StSOLv1.1ch01.Colomba/Mapped/shortReads/StSOLv1.1ch01.Colomba.sorted.MD.bam": No such file or directory

**Comment by nPhasePipeline** [comment] 2020-09-24 13:05
Hi, thank you for reporting this bug. If you'd rather not wait for me to release a new version of nPhase, you can fix it manually by manually editing the file /media/bulk_01/users/essel002/anaconda3/envs/polyploidPhasing/lib/python3.8/site-packages/bin/nPhasePipeline.py to replace "shortReadBam==args.mappedShortReads" in line 333 by "shortReadBam=args.mappedShortReads" (only removing one "=" sign). Otherwise I will be fixing it soon. Once I close this issue you will be able to run

conda update nphase -c oakheart

To get a new version which has a fix for the problem you reported.

For your error with the full pipeline, GATK is saying that it ran out of memory:

"Exception in thread "main" java.lang.OutOfMemoryError: Java heap space", so this is not a bug with nPhase. You can try it again by assigning more memory to the job if you wish.

**Comment by nPhasePipeline** [comment] 2020-10-05 10:20
Fixed in v1.0.12

**Closed by nPhasePipeline** 2020-10-05 10:20 UTC
